// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeXWSSy121YKZ18s9MVb6eM6OR-42NqGM',
    appId: '1:60561012964:web:cf8c421d7a50e31a1094f1',
    messagingSenderId: '60561012964',
    projectId: 'inventory-management-0809',
    authDomain: 'inventory-management-0809.firebaseapp.com',
    storageBucket: 'inventory-management-0809.firebasestorage.app',
    measurementId: 'G-YYGL9PT3HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaQXzrry9cBqTQO3sxb_TqGShSn1uNkFg',
    appId: '1:60561012964:android:83bb37f486168aab1094f1',
    messagingSenderId: '60561012964',
    projectId: 'inventory-management-0809',
    storageBucket: 'inventory-management-0809.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMz3kd8SBNbmerq8hFAY99BZZiX7iJV40',
    appId: '1:60561012964:ios:df0f9f1b5a42b7751094f1',
    messagingSenderId: '60561012964',
    projectId: 'inventory-management-0809',
    storageBucket: 'inventory-management-0809.firebasestorage.app',
    iosClientId: '60561012964-vvlaakfurg0vqeav1ft02sgs4t48gbub.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyuser',
  );
}
