// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwiMuuipmNubrVzHxfcWAA4tMQCi8U1CM',
    appId: '1:76902832747:web:274c73fefe5872ed81ef2e',
    messagingSenderId: '76902832747',
    projectId: 'dil-se-deliver',
    authDomain: 'dil-se-deliver.firebaseapp.com',
    storageBucket: 'dil-se-deliver.firebasestorage.app',
    measurementId: 'G-1FLWF77GYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEHlRuIyrataAQAvrgaSRbMVLj2obCR3o',
    appId: '1:76902832747:android:2ecc171f4a34110281ef2e',
    messagingSenderId: '76902832747',
    projectId: 'dil-se-deliver',
    storageBucket: 'dil-se-deliver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4OzQYzSy1Stf6bYN-DLwukKGNXUB3omw',
    appId: '1:76902832747:ios:0af1049f326bf2f581ef2e',
    messagingSenderId: '76902832747',
    projectId: 'dil-se-deliver',
    storageBucket: 'dil-se-deliver.firebasestorage.app',
    iosBundleId: 'com.example.forkIt',
  );
}
